version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: secugen_db
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      app_network:
        ipv4_address: 192.168.100.2

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: secugen_api
    restart: always
    network_mode: "host"
    environment:
      - DB_HOST=192.168.100.2
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    privileged: true
    devices:
      - "/dev/bus/usb/002/002:/dev/bus/usb/002/002"
    volumes:
      - /dev/bus/usb/002/002:/dev/bus/usb/002/002

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24

volumes:
  db_data: 